name: Publish docs update

on:
  push:
    branches: [beta7, early, stable7]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        env:
          API_TOKEN_GITHUB: ${{ secrets.PLENTY_ACTION_TOKEN }}
            
      - name: Rebuild site
        run: |
          curl -X POST https://api.github.com/repos/plentymarkets/plenty-developers-docs/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u 'plentymarkets: $API_TOKEN_GITHUB' \
          --data '{"event_type": "ContentSourceUpdate", "client_payload": { "repository": "'{{ $GITHUB_REPOSITORY }}'" }}'
